AWSTemplateFormatVersion: 2010-09-09
Description: 'A template to run the gatling env for stress testing.'
Parameters:
 VPCId:
    Description: VPC id
    Type: String
 Ec2key:
    Description: Instance Key
    Type: String
Resources:
  SGGatling:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Gatling Security Group
      VpcId:
       Ref: VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 208.78.232.7/32
          FromPort: 22
          ToPort: 22
  GatlingServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0b59bfac6be064b78
      KeyName:
       Ref: Ec2key
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "SGGatling"  
Outputs: 
 PublicIp: 
  Value: 
   "Fn::GetAtt": 
    - GatlingServer
    - PublicIp
  Description: "Gatling Server's PublicIp Address"