---

- name: Update yum repos
  become: yes
  yum:
    name: '*'
    state: latest

- name: Install software dependencies
  become: yes
  yum:
    name: "{{ system_packages }}"
    state: latest
  vars:
    system_packages:
      - htop
      - git
      - python3
      - python3-pip
      - sysstat
      - java-1.8.0-openjdk
      - zip
      - unzip

- name: Upgrade pip3
  pip:
    executable: /usr/local/bin/pip3
    name: pip
    extra_args: --upgrade

- name: Install pip packages
  become: yes
  pip:
    name: "{{ pip_packages }}"
    state: latest
    executable: /usr/local/bin/pip3
  vars:
    pip_packages:
      - awscli

- name: Create Gatling directory
  file:
    owner: ec2-user 
    group: ec2-user
    mode: 0775
    state: directory
    path: /opt/gatling

- name: Unzip Gatling 
  unarchive:
    remote_src: yes
    src: https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.0.1.1/gatling-charts-highcharts-bundle-3.0.1.1-bundle.zip
    creates: /home/ec2-user/gatling-charts-highcharts-bundle-3.0.1.1/bin/gatling.sh
    dest: /home/ec2-user/

- name: stat home path
  stat:
    path: /home/ec2-user/gatling-charts-highcharts-bundle-3.0.1.1/LICENSE
  register: home_gatling_stat

- name: stat opt path
  stat:
    path: /opt/gatling/LICENSE
  register: opt_gatling_stat

- name: Move to a shorter path
  shell: cp -R /home/ec2-user/gatling-charts-highcharts-bundle-3.0.1.1/* /opt/gatling/
  when: home_gatling_stat.stat.exists and opt_gatling_stat.stat.exists == False 

- name: Remove extra files
  file:
    path: "/opt/gatling/{{ item }}"
    state: absent
  with_items:
    - "bin/gatling.bat"
    - "bin/recorder.bat"
    - "user-files/resources/search.csv"
    - "user-files/simulations/computerdatabase"

- name: Change file ownership
  file:
    path: /opt/gatling
    group: ec2-user
    owner: ec2-user
    mode: 0775
    recurse: yes
      
- name: Copy URL list and request body
  copy:
    owner: ec2-user
    group: ec2-user
    mode: 0775
    src: "{{ item }}"
    dest: /opt/gatling/user-files/resources/
  with_items:
    - urls.csv
    - body.json

- name: Copy Gatling scenario definition
  template:
    owner: ec2-user
    group: ec2-user
    mode: 0775
    src: gamechanger_load_test.scala.j2
    dest: /opt/gatling/user-files/simulations/gamechanger_load_test.scala

- name: Copy run script
  copy:
    owner: ec2-user
    group: ec2-user
    mode: 0775
    src: run_gatling.sh
    dest: /home/ec2-user/run_gatling.sh
